<table class="ui red table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui orange table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui yellow table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
  </table>
<table class="ui olive table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui green table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui teal table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui blue table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui violet table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui purple table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui pink table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui grey table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>
<table class="ui black table">
  <thead>
    <tr><th>Food</th>
    <th>Calories</th>
    <th>Protein</th>
  </tr></thead><tbody>
    <tr>
      <td>Apples</td>
      <td>200</td>
      <td>0g</td>
    </tr>
    <tr>
      <td>Orange</td>
      <td>310</td>
      <td>0g</td>
    </tr>
  </tbody>
</table>